import Providers from "@/lib/Providers";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SocketContextProvider } from "@/socket/socket";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "WhatsApp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html lang="en">
        <SocketContextProvider>
          <body className={inter.className}>{children}</body>
        </SocketContextProvider>
      </html>
    </Providers>
  );
}
